### ISSUE TITLE
Thanks for creating the Consul adapter for Casbin

### ISSUE THREAD

**Issue by hsluoyz** [ankitm123/consul_adapter#1]
Hi @ankitm123 ,

I have been noticing this repo silently for days, and I'm glad to see that you make a great progress on the Consul adapter for Casbin. Thanks for doing all this!

My question here is, can I add a link to this repo in [Casbin' README.md](https://github.com/casbin/casbin)? I'd like to maintain a list for all official and 3rd-party adapters. Let me know if you have other questions:)

**Comment by ankitm123** [comment]
Hi @hsluoyz,

Thanks for taking a look at the repo. I still have to commit the test file. I do have some questions:

1.  Why don't the LoadPolicy and SavePolicy return errors? https://github.com/casbin/casbin/blob/master/persist/adapter.go#L41

2. I see lot of panics in the code, don't you think it might be better to handle the errors properly rather than panic?

It would be nice if you link the repo in the casbin Readme. 
Ankit

**Comment by hsluoyz** [comment]
These two questions are mostly the same one question: **why Casbin uses panic more than error?**

There's already a conversation about it here: https://github.com/casbin/casbin/issues/19

And I once tried to rewrite all panics to errors, but then I found the debugging becomes difficult. Because panic will directly provide the faulting call stack, it shows which code line is faulty. But when I use errors, even I print the error to standard output, it's just a string. The call stack is missing. I have to search the error text to locate the faulty position. Not to mention if we have same error texts for multiple code lines.

You may think that we can still use ``panic(err)`` to turn an error into a panic. But the call stack it triggered is actually for the moment of the panic call. The call stack for the original error is no way to recover.

But the other way around, turning a panic into error is very easy and doesn't lose anything. For example, to wrap the ``Enforce()`` function, we can use:

```go
// EnforceSafe calls Enforce in a safe way, returns error instead of causing panic.
func (e *Enforcer) EnforceSafe(rvals ...string) (result bool, err error) {
	defer func() {
		if r := recover(); r != nil {
			switch x := r.(type) {
			case string:
				err = errors.New(x)
			case error:
				err = x
			default:
				err = errors.New("Unknown panic")
			}

			result = false
		}
	}()

	result = e.Enforce(rvals...)
	err = nil
	return
}
```

So I provide the _Safe functions as the workaround. They will turn any panic into errors.

```go
func NewEnforcerSafe(params ...interface{}) (e *Enforcer, err error) {}
func (e *Enforcer) EnforceSafe(rvals ...string) (result bool, err error) {}
func (e *Enforcer) LoadModelSafe() (err error) {}
func (e *Enforcer) LoadPolicySafe() (err error) {}
func (e *Enforcer) SavePolicySafe() (err error) {}
```

All the adapters are called in ``LoadPolicy`` and ``SavePolicy``, so they are covered by these adapters.

So simply speaking:

1. Using panic or errors inside Casbin doesn't affect the public API. Casbin users can choose to use the _Safe functions to get error instead of panic.

2. Using panic inside Casbin can helps debugging.
